/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ironman.gltf 
Author: 9A Films / Nihar Arora (https://sketchfab.com/Nihar-9Afilms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-man-mark-85-nano-tech-arc-reactor-free-7686cfc26b68477cb64d33a467c9f9bf
Title: Iron-Man Mark 85 | Nano-Tech Arc Reactor | Free
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ironman.gltf')
  const { actions } = useAnimations(animations, group)
  const rotationSpeed = 0.8;
  useFrame((state, delta) => {
    if (props.rotate) {
      group.current.rotation.y += rotationSpeed * delta;
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <ambientLight intensity={1} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="35988332074843e89a7f3e081ed48c1afbx" rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Point001" position={[0, 0.136, 18.973]} rotation={[0, -1.571, 0]}>
                  <group name="Endgame" position={[4.429, 21.937, -0.112]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                    <group name="Arc_Reactor" position={[0, 10.757, 0]} rotation={[-1.92, 0, 0]} scale={[-0.261, -0.177, -0.416]}>
                      <group name="Object_7" position={[-7.457, 36.978, 1.931]}>
                        <mesh name="Arc_Reactor_Arc_Reactor_0" geometry={nodes.Arc_Reactor_Arc_Reactor_0.geometry} material={materials.Arc_Reactor} />
                        <mesh name="Arc_Reactor_Arc_Reactor_0_1" geometry={nodes.Arc_Reactor_Arc_Reactor_0_1.geometry} material={materials.Arc_Reactor} />
                      </group>
                      <group name="Core" position={[0, -10.729, -1.571]}>
                        <group name="Object_11" position={[-7.457, 47.707, 3.502]}>
                          <mesh name="Core_Core_Nanotech_0" geometry={nodes.Core_Core_Nanotech_0.geometry} material={materials.Core_Nanotech} />
                        </group>
                      </group>
                    </group>
                    <group name="Nano_Stand" position={[-0.112, 7.099, -11.016]}>
                      <group name="Base" position={[0.474, 13.355, -10.212]} rotation={[Math.PI, 0, 0]} scale={[-0.878, -0.758, -0.404]}>
                        <group name="Object_15" position={[0.002, -1.826, -2.555]}>
                          <mesh name="Base_Material_#41_0" geometry={nodes['Base_Material_#41_0'].geometry} material={materials.Material_41} />
                          <mesh name="Base_Material_#42_0" geometry={nodes['Base_Material_#42_0'].geometry} material={materials.Material_42} />
                        </group>
                      </group>
                      <group name="Main_Base" position={[0, -3.093, -11.057]} scale={0.793}>
                        <mesh name="Main_Base_Material_#29_0" geometry={nodes['Main_Base_Material_#29_0'].geometry} material={materials.Material_29} />
                        <mesh name="Main_Base_Material_#28_0" geometry={nodes['Main_Base_Material_#28_0'].geometry} material={materials.Material_28} />
                      </group>
                      <group name="A" position={[0, -3.878, -8.041]} scale={0.818}>
                        <group name="Object_22" position={[-14.247, 1.319, -3.39]}>
                          <mesh name="A_Material_#28_0" geometry={nodes['A_Material_#28_0'].geometry} material={materials.Material_28} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ironman.gltf')